server:
  port: 9090
spring:
  datasource:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liangzai?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  rabbitmq:
    username: user
    password: user
    virtual-host: /user
    addresses: 127.0.0.1:5672

